### PR TITLE
Update darkmode based on new experimental palette

### PR DESCRIPTION
**Pull request by PavelHolec**
Using few experimental dark mode colors from figma

https://www.figma.com/file/bpXcYuAuuhYAdrJoT2U7yz/Dark-mode?node-id=0%3A1

image

image

image

image

### CODE REVIEW

**Review by username0x0a — APPROVED** [review]
🤩

**Comment by username0x0a** [comment]
There's a couple of padding moves, yet some snapshots seem to lose the padding completely – is that on purpose, like do we only retain it on actual Previews for human-readable cases? 🤔

**Comment by PavelHolec** [comment]
> There's a couple of padding moves, yet some snapshots seem to lose the padding completely – is that on purpose, like do we only retain it on actual Previews for human-readable cases? 🤔

I will recheck the previews. In general, the Storybook-related paddings have been moved out to unified layout. Will add .medium paddings back to specific previews where they are now missing.

**Comment by hrach** [comment]
So in Compose, we have those colored secondary buttons on Alert rather lighter than darker then the alert's background. Similarly the button is darker than the bg in light mode. Is this intentional?

**Comment by PavelHolec** [comment]
> So in Compose, we have those colored secondary buttons on Alert rather lighter than darker then the alert's background. Similarly the button is darker than the bg in light mode. Is this intentional?

This task is using only the figma colors as direct replacement of existing palette colors. No additional surface/opacity etc. logic is added yet - waiting for more progress from Orbit.

**Comment by PavelHolec** [comment]
> So in Compose, we have those colored secondary buttons on Alert rather lighter than darker then the alert's background. Similarly the button is darker than the bg in light mode. Is this intentional?

Will recheck - I probably missed some of WIP colors from figma.

**Comment by hrach** [comment]
Those colors weren't present at all in Figma, if you don't have a different file. I made them 10% lighter.

**Comment by PavelHolec** [comment]
> 

Did with similar offsets (also for active+hover), updated.

**Comment by PavelHolec** [comment]
> Those colors weren't present at all in Figma, if you don't have a different file. I made them 10% lighter.

Did it similar with similar offsets (also for active+hover), updated.

**Pull request merged**
